/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: decoder.i

package glue

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef _gostring_ swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef _gostring_ swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef void* swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
extern void _wrap_Swig_free_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_glue_5245479e8dc75ce4(swig_intgo arg1);
extern swig_intgo _wrap_JXL_TYPE_FLOAT_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_TYPE_BOOLEAN_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_TYPE_UINT8_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_TYPE_UINT16_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_TYPE_UINT32_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_TYPE_FLOAT16_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_NATIVE_ENDIAN_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_LITTLE_ENDIAN_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_BIG_ENDIAN_glue_5245479e8dc75ce4(void);
extern void _wrap_JxlPixelFormat_num_channels_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlPixelFormat_num_channels_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlPixelFormat_data_type_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlPixelFormat_data_type_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlPixelFormat_endianness_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlPixelFormat_endianness_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlPixelFormat_align_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_JxlPixelFormat_align_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlPixelFormat_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlPixelFormat_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JxlDecoderVersion_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_SIG_NOT_ENOUGH_BYTES_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_SIG_INVALID_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_SIG_CODESTREAM_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_SIG_CONTAINER_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JxlSignatureCheck_glue_5245479e8dc75ce4(swig_voidp arg1, swig_type_3 arg2);
extern uintptr_t _wrap_JxlDecoderCreate_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlDecoderReset_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlDecoderDestroy_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JXL_DEC_SUCCESS_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_ERROR_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_NEED_MORE_INPUT_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_NEED_PREVIEW_OUT_BUFFER_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_NEED_DC_OUT_BUFFER_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_NEED_IMAGE_OUT_BUFFER_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_JPEG_NEED_MORE_OUTPUT_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_BASIC_INFO_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_EXTENSIONS_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_COLOR_ENCODING_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_PREVIEW_IMAGE_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_FRAME_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_DC_IMAGE_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_FULL_IMAGE_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_DEC_JPEG_RECONSTRUCTION_glue_5245479e8dc75ce4(void);
extern void _wrap_JxlDecoderRewind_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlDecoderSkipFrames_glue_5245479e8dc75ce4(uintptr_t arg1, swig_type_4 arg2);
extern swig_intgo _wrap_JxlDecoderDefaultPixelFormat_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_JxlDecoderSetParallelRunner_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_type_5 _wrap_JxlDecoderSizeHintBasicInfo_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JxlDecoderSubscribeEvents_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlDecoderSetKeepOrientation_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlDecoderProcessInput_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JxlDecoderSetInput_glue_5245479e8dc75ce4(uintptr_t arg1, swig_voidp arg2, swig_type_6 arg3);
extern swig_type_7 _wrap_JxlDecoderReleaseInput_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JxlDecoderGetBasicInfo_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_JxlDecoderGetExtraChannelInfo_glue_5245479e8dc75ce4(uintptr_t arg1, swig_type_8 arg2, uintptr_t arg3);
extern swig_intgo _wrap_JxlDecoderGetExtraChannelName_glue_5245479e8dc75ce4(uintptr_t arg1, swig_type_9 arg2, swig_type_10 arg3, swig_type_11 arg4);
extern swig_intgo _wrap_JXL_COLOR_PROFILE_TARGET_ORIGINAL_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_COLOR_PROFILE_TARGET_DATA_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JxlDecoderGetColorAsEncodedProfile_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, uintptr_t arg4);
extern swig_intgo _wrap_JxlDecoderGetICCProfileSize_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_voidp arg4);
extern swig_intgo _wrap_JxlDecoderGetColorAsICCProfile_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_voidp arg4, swig_type_12 arg5);
extern swig_intgo _wrap_JxlDecoderSetPreferredColorProfile_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_JxlDecoderPreviewOutBufferSize_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_JxlDecoderSetPreviewOutBuffer_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_13 arg4);
extern swig_intgo _wrap_JxlDecoderGetFrameHeader_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_JxlDecoderGetFrameName_glue_5245479e8dc75ce4(uintptr_t arg1, swig_type_14 arg2, swig_type_15 arg3);
extern swig_intgo _wrap_JxlDecoderImageOutBufferSize_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern swig_intgo _wrap_JxlDecoderSetImageOutBuffer_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_16 arg4);
extern swig_intgo _wrap_JxlDecoderSetImageOutCallback_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_type_17 arg3, uintptr_t arg4);
extern swig_intgo _wrap_JxlDecoderExtraChannelBufferSize_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3, swig_intgo arg4);
extern swig_intgo _wrap_JxlDecoderSetExtraChannelBuffer_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_18 arg4, swig_intgo arg5);
extern swig_intgo _wrap_JxlDecoderSetJPEGBuffer_glue_5245479e8dc75ce4(uintptr_t arg1, swig_voidp arg2, swig_type_19 arg3);
extern swig_type_20 _wrap_JxlDecoderReleaseJPEGBuffer_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JxlDecoderFlushImage_glue_5245479e8dc75ce4(uintptr_t arg1);
extern swig_intgo _wrap_JXL_ORIENT_IDENTITY_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_FLIP_HORIZONTAL_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_ROTATE_180_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_FLIP_VERTICAL_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_TRANSPOSE_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_ROTATE_90_CW_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_ANTI_TRANSPOSE_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_ORIENT_ROTATE_90_CCW_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_ALPHA_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_DEPTH_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_SPOT_COLOR_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_SELECTION_MASK_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_BLACK_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_CFA_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_THERMAL_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED0_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED1_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED2_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED3_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED4_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED5_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED6_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_RESERVED7_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_UNKNOWN_glue_5245479e8dc75ce4(void);
extern swig_intgo _wrap_JXL_CHANNEL_OPTIONAL_glue_5245479e8dc75ce4(void);
extern void _wrap_JxlPreviewHeader_xsize_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlPreviewHeader_xsize_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlPreviewHeader_ysize_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlPreviewHeader_ysize_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlPreviewHeader_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlPreviewHeader_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlAnimationHeader_tps_numerator_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlAnimationHeader_tps_numerator_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlAnimationHeader_tps_denominator_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlAnimationHeader_tps_denominator_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlAnimationHeader_num_loops_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlAnimationHeader_num_loops_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlAnimationHeader_have_timecodes_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlAnimationHeader_have_timecodes_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlAnimationHeader_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlAnimationHeader_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_have_container_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_have_container_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_xsize_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_xsize_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_ysize_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_ysize_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_bits_per_sample_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_bits_per_sample_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_exponent_bits_per_sample_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_exponent_bits_per_sample_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_intensity_target_set_glue_5245479e8dc75ce4(uintptr_t arg1, float arg2);
extern float _wrap_JxlBasicInfo_intensity_target_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_min_nits_set_glue_5245479e8dc75ce4(uintptr_t arg1, float arg2);
extern float _wrap_JxlBasicInfo_min_nits_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_relative_to_max_display_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_relative_to_max_display_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_linear_below_set_glue_5245479e8dc75ce4(uintptr_t arg1, float arg2);
extern float _wrap_JxlBasicInfo_linear_below_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_uses_original_profile_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_uses_original_profile_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_have_preview_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_have_preview_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_have_animation_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_have_animation_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_orientation_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_orientation_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_num_color_channels_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_num_color_channels_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_num_extra_channels_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_num_extra_channels_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_alpha_bits_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_alpha_bits_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_alpha_exponent_bits_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_alpha_exponent_bits_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_alpha_premultiplied_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlBasicInfo_alpha_premultiplied_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_preview_set_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_JxlBasicInfo_preview_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_animation_set_glue_5245479e8dc75ce4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_JxlBasicInfo_animation_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlBasicInfo_padding_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_JxlBasicInfo_padding_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlBasicInfo_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlBasicInfo_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_Xtype_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_Xtype_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_bits_per_sample_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_bits_per_sample_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_exponent_bits_per_sample_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_exponent_bits_per_sample_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_dim_shift_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_dim_shift_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_name_length_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_name_length_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_alpha_premultiplied_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_alpha_premultiplied_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_spot_color_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_JxlExtraChannelInfo_spot_color_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlExtraChannelInfo_cfa_channel_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlExtraChannelInfo_cfa_channel_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlExtraChannelInfo_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlExtraChannelInfo_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlHeaderExtensions_extensions_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_type_21 arg2);
extern swig_type_22 _wrap_JxlHeaderExtensions_extensions_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlHeaderExtensions_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlHeaderExtensions_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlFrameHeader_duration_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlFrameHeader_duration_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlFrameHeader_timecode_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlFrameHeader_timecode_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlFrameHeader_name_length_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlFrameHeader_name_length_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern void _wrap_JxlFrameHeader_is_last_set_glue_5245479e8dc75ce4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_JxlFrameHeader_is_last_get_glue_5245479e8dc75ce4(uintptr_t arg1);
extern uintptr_t _wrap_new_JxlFrameHeader_glue_5245479e8dc75ce4(void);
extern void _wrap_delete_JxlFrameHeader_glue_5245479e8dc75ce4(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_glue_5245479e8dc75ce4(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const JXL_TRUE int = 1
const JXL_FALSE int = 0
type JxlDataType int
func _swig_getJXL_TYPE_FLOAT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_TYPE_FLOAT_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_TYPE_FLOAT int = _swig_getJXL_TYPE_FLOAT()
func _swig_getJXL_TYPE_BOOLEAN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_TYPE_BOOLEAN_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_TYPE_BOOLEAN int = _swig_getJXL_TYPE_BOOLEAN()
func _swig_getJXL_TYPE_UINT8() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_TYPE_UINT8_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_TYPE_UINT8 int = _swig_getJXL_TYPE_UINT8()
func _swig_getJXL_TYPE_UINT16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_TYPE_UINT16_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_TYPE_UINT16 int = _swig_getJXL_TYPE_UINT16()
func _swig_getJXL_TYPE_UINT32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_TYPE_UINT32_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_TYPE_UINT32 int = _swig_getJXL_TYPE_UINT32()
func _swig_getJXL_TYPE_FLOAT16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_TYPE_FLOAT16_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_TYPE_FLOAT16 int = _swig_getJXL_TYPE_FLOAT16()
type JxlEndianness int
func _swig_getJXL_NATIVE_ENDIAN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_NATIVE_ENDIAN_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_NATIVE_ENDIAN int = _swig_getJXL_NATIVE_ENDIAN()
func _swig_getJXL_LITTLE_ENDIAN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_LITTLE_ENDIAN_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_LITTLE_ENDIAN int = _swig_getJXL_LITTLE_ENDIAN()
func _swig_getJXL_BIG_ENDIAN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_BIG_ENDIAN_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_BIG_ENDIAN int = _swig_getJXL_BIG_ENDIAN()
type SwigcptrJxlPixelFormat uintptr

func (p SwigcptrJxlPixelFormat) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlPixelFormat) SwigIsJxlPixelFormat() {
}

func (arg1 SwigcptrJxlPixelFormat) SetNum_channels(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlPixelFormat_num_channels_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlPixelFormat) GetNum_channels() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlPixelFormat_num_channels_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlPixelFormat) SetData_type(arg2 JxlDataType) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlPixelFormat_data_type_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlPixelFormat) GetData_type() (_swig_ret JxlDataType) {
	var swig_r JxlDataType
	_swig_i_0 := arg1
	swig_r = (JxlDataType)(C._wrap_JxlPixelFormat_data_type_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlPixelFormat) SetEndianness(arg2 JxlEndianness) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlPixelFormat_endianness_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlPixelFormat) GetEndianness() (_swig_ret JxlEndianness) {
	var swig_r JxlEndianness
	_swig_i_0 := arg1
	swig_r = (JxlEndianness)(C._wrap_JxlPixelFormat_endianness_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlPixelFormat) SetAlign(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlPixelFormat_align_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrJxlPixelFormat) GetAlign() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_JxlPixelFormat_align_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlPixelFormat() (_swig_ret JxlPixelFormat) {
	var swig_r JxlPixelFormat
	swig_r = (JxlPixelFormat)(SwigcptrJxlPixelFormat(C._wrap_new_JxlPixelFormat_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlPixelFormat(arg1 JxlPixelFormat) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlPixelFormat_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlPixelFormat interface {
	Swigcptr() uintptr
	SwigIsJxlPixelFormat()
	SetNum_channels(arg2 uint)
	GetNum_channels() (_swig_ret uint)
	SetData_type(arg2 JxlDataType)
	GetData_type() (_swig_ret JxlDataType)
	SetEndianness(arg2 JxlEndianness)
	GetEndianness() (_swig_ret JxlEndianness)
	SetAlign(arg2 int64)
	GetAlign() (_swig_ret int64)
}

func JxlDecoderVersion() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_JxlDecoderVersion_glue_5245479e8dc75ce4())
	return swig_r
}

type JxlSignature int
func _swig_getJXL_SIG_NOT_ENOUGH_BYTES() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_SIG_NOT_ENOUGH_BYTES_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_SIG_NOT_ENOUGH_BYTES int = _swig_getJXL_SIG_NOT_ENOUGH_BYTES()
func _swig_getJXL_SIG_INVALID() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_SIG_INVALID_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_SIG_INVALID int = _swig_getJXL_SIG_INVALID()
func _swig_getJXL_SIG_CODESTREAM() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_SIG_CODESTREAM_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_SIG_CODESTREAM int = _swig_getJXL_SIG_CODESTREAM()
func _swig_getJXL_SIG_CONTAINER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_SIG_CONTAINER_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_SIG_CONTAINER int = _swig_getJXL_SIG_CONTAINER()
func JxlSignatureCheck(arg1 *byte, arg2 int64) (_swig_ret JxlSignature) {
	var swig_r JxlSignature
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (JxlSignature)(C._wrap_JxlSignatureCheck_glue_5245479e8dc75ce4(C.swig_voidp(_swig_i_0), C.swig_type_3(_swig_i_1)))
	return swig_r
}

func JxlDecoderCreate(arg1 JxlMemoryManager) (_swig_ret JxlDecoderStruct) {
	var swig_r JxlDecoderStruct
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (JxlDecoderStruct)(SwigcptrJxlDecoderStruct(C._wrap_JxlDecoderCreate_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func JxlDecoderReset(arg1 JxlDecoderStruct) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_JxlDecoderReset_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

func JxlDecoderDestroy(arg1 JxlDecoderStruct) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_JxlDecoderDestroy_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlDecoderStatus int
func _swig_getJXL_DEC_SUCCESS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_SUCCESS_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_SUCCESS int = _swig_getJXL_DEC_SUCCESS()
func _swig_getJXL_DEC_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_ERROR_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_ERROR int = _swig_getJXL_DEC_ERROR()
func _swig_getJXL_DEC_NEED_MORE_INPUT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_NEED_MORE_INPUT_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_NEED_MORE_INPUT int = _swig_getJXL_DEC_NEED_MORE_INPUT()
func _swig_getJXL_DEC_NEED_PREVIEW_OUT_BUFFER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_NEED_PREVIEW_OUT_BUFFER_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_NEED_PREVIEW_OUT_BUFFER int = _swig_getJXL_DEC_NEED_PREVIEW_OUT_BUFFER()
func _swig_getJXL_DEC_NEED_DC_OUT_BUFFER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_NEED_DC_OUT_BUFFER_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_NEED_DC_OUT_BUFFER int = _swig_getJXL_DEC_NEED_DC_OUT_BUFFER()
func _swig_getJXL_DEC_NEED_IMAGE_OUT_BUFFER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_NEED_IMAGE_OUT_BUFFER_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_NEED_IMAGE_OUT_BUFFER int = _swig_getJXL_DEC_NEED_IMAGE_OUT_BUFFER()
func _swig_getJXL_DEC_JPEG_NEED_MORE_OUTPUT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_JPEG_NEED_MORE_OUTPUT_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_JPEG_NEED_MORE_OUTPUT int = _swig_getJXL_DEC_JPEG_NEED_MORE_OUTPUT()
func _swig_getJXL_DEC_BASIC_INFO() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_BASIC_INFO_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_BASIC_INFO int = _swig_getJXL_DEC_BASIC_INFO()
func _swig_getJXL_DEC_EXTENSIONS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_EXTENSIONS_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_EXTENSIONS int = _swig_getJXL_DEC_EXTENSIONS()
func _swig_getJXL_DEC_COLOR_ENCODING() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_COLOR_ENCODING_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_COLOR_ENCODING int = _swig_getJXL_DEC_COLOR_ENCODING()
func _swig_getJXL_DEC_PREVIEW_IMAGE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_PREVIEW_IMAGE_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_PREVIEW_IMAGE int = _swig_getJXL_DEC_PREVIEW_IMAGE()
func _swig_getJXL_DEC_FRAME() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_FRAME_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_FRAME int = _swig_getJXL_DEC_FRAME()
func _swig_getJXL_DEC_DC_IMAGE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_DC_IMAGE_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_DC_IMAGE int = _swig_getJXL_DEC_DC_IMAGE()
func _swig_getJXL_DEC_FULL_IMAGE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_FULL_IMAGE_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_FULL_IMAGE int = _swig_getJXL_DEC_FULL_IMAGE()
func _swig_getJXL_DEC_JPEG_RECONSTRUCTION() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_DEC_JPEG_RECONSTRUCTION_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_DEC_JPEG_RECONSTRUCTION int = _swig_getJXL_DEC_JPEG_RECONSTRUCTION()
func JxlDecoderRewind(arg1 JxlDecoderStruct) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_JxlDecoderRewind_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

func JxlDecoderSkipFrames(arg1 JxlDecoderStruct, arg2 int64) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_JxlDecoderSkipFrames_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func JxlDecoderDefaultPixelFormat(arg1 JxlDecoderStruct, arg2 JxlPixelFormat) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderDefaultPixelFormat_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func JxlDecoderSetParallelRunner(arg1 JxlDecoderStruct, arg2 JxlParallelRunner, arg3 uintptr) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetParallelRunner_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func JxlDecoderSizeHintBasicInfo(arg1 JxlDecoderStruct) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int64)(C._wrap_JxlDecoderSizeHintBasicInfo_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func JxlDecoderSubscribeEvents(arg1 JxlDecoderStruct, arg2 int) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSubscribeEvents_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func JxlDecoderSetKeepOrientation(arg1 JxlDecoderStruct, arg2 int) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetKeepOrientation_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func JxlDecoderProcessInput(arg1 JxlDecoderStruct) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderProcessInput_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func JxlDecoderSetInput(arg1 JxlDecoderStruct, arg2 *byte, arg3 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetInput_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_6(_swig_i_2)))
	return swig_r
}

func JxlDecoderReleaseInput(arg1 JxlDecoderStruct) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int64)(C._wrap_JxlDecoderReleaseInput_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func JxlDecoderGetBasicInfo(arg1 JxlDecoderStruct, arg2 JxlBasicInfo) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetBasicInfo_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func JxlDecoderGetExtraChannelInfo(arg1 JxlDecoderStruct, arg2 int64, arg3 JxlExtraChannelInfo) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetExtraChannelInfo_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func JxlDecoderGetExtraChannelName(arg1 JxlDecoderStruct, arg2 int64, arg3 string, arg4 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetExtraChannelName_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_type_9(_swig_i_1), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_2)), C.swig_type_11(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

type JxlColorProfileTarget int
func _swig_getJXL_COLOR_PROFILE_TARGET_ORIGINAL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_COLOR_PROFILE_TARGET_ORIGINAL_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_COLOR_PROFILE_TARGET_ORIGINAL int = _swig_getJXL_COLOR_PROFILE_TARGET_ORIGINAL()
func _swig_getJXL_COLOR_PROFILE_TARGET_DATA() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_COLOR_PROFILE_TARGET_DATA_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_COLOR_PROFILE_TARGET_DATA int = _swig_getJXL_COLOR_PROFILE_TARGET_DATA()
func JxlDecoderGetColorAsEncodedProfile(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 JxlColorProfileTarget, arg4 JxlColorEncoding) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetColorAsEncodedProfile_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), C.uintptr_t(_swig_i_3)))
	return swig_r
}

func JxlDecoderGetICCProfileSize(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 JxlColorProfileTarget, arg4 *int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetICCProfileSize_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func JxlDecoderGetColorAsICCProfile(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 JxlColorProfileTarget, arg4 *byte, arg5 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetColorAsICCProfile_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_type_12(_swig_i_4)))
	return swig_r
}

func JxlDecoderSetPreferredColorProfile(arg1 JxlDecoderStruct, arg2 JxlColorEncoding) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetPreferredColorProfile_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func JxlDecoderPreviewOutBufferSize(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 *int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderPreviewOutBufferSize_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func JxlDecoderSetPreviewOutBuffer(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 uintptr, arg4 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetPreviewOutBuffer_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_13(_swig_i_3)))
	return swig_r
}

func JxlDecoderGetFrameHeader(arg1 JxlDecoderStruct, arg2 JxlFrameHeader) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetFrameHeader_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func JxlDecoderGetFrameName(arg1 JxlDecoderStruct, arg2 string, arg3 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderGetFrameName_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1)), C.swig_type_15(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func JxlDecoderImageOutBufferSize(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 *int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderImageOutBufferSize_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func JxlDecoderSetImageOutBuffer(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 uintptr, arg4 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetImageOutBuffer_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_16(_swig_i_3)))
	return swig_r
}

func JxlDecoderSetImageOutCallback(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 _swig_fnptr, arg4 uintptr) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetImageOutCallback_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_17(_swig_i_2), C.uintptr_t(_swig_i_3)))
	return swig_r
}

func JxlDecoderExtraChannelBufferSize(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 *int64, arg4 uint) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderExtraChannelBufferSize_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func JxlDecoderSetExtraChannelBuffer(arg1 JxlDecoderStruct, arg2 JxlPixelFormat, arg3 uintptr, arg4 int64, arg5 uint) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetExtraChannelBuffer_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_18(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func JxlDecoderSetJPEGBuffer(arg1 JxlDecoderStruct, arg2 *byte, arg3 int64) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderSetJPEGBuffer_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_type_19(_swig_i_2)))
	return swig_r
}

func JxlDecoderReleaseJPEGBuffer(arg1 JxlDecoderStruct) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int64)(C._wrap_JxlDecoderReleaseJPEGBuffer_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func JxlDecoderFlushImage(arg1 JxlDecoderStruct) (_swig_ret JxlDecoderStatus) {
	var swig_r JxlDecoderStatus
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (JxlDecoderStatus)(C._wrap_JxlDecoderFlushImage_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type JxlOrientation int
func _swig_getJXL_ORIENT_IDENTITY() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_IDENTITY_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_IDENTITY int = _swig_getJXL_ORIENT_IDENTITY()
func _swig_getJXL_ORIENT_FLIP_HORIZONTAL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_FLIP_HORIZONTAL_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_FLIP_HORIZONTAL int = _swig_getJXL_ORIENT_FLIP_HORIZONTAL()
func _swig_getJXL_ORIENT_ROTATE_180() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_ROTATE_180_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_ROTATE_180 int = _swig_getJXL_ORIENT_ROTATE_180()
func _swig_getJXL_ORIENT_FLIP_VERTICAL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_FLIP_VERTICAL_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_FLIP_VERTICAL int = _swig_getJXL_ORIENT_FLIP_VERTICAL()
func _swig_getJXL_ORIENT_TRANSPOSE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_TRANSPOSE_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_TRANSPOSE int = _swig_getJXL_ORIENT_TRANSPOSE()
func _swig_getJXL_ORIENT_ROTATE_90_CW() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_ROTATE_90_CW_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_ROTATE_90_CW int = _swig_getJXL_ORIENT_ROTATE_90_CW()
func _swig_getJXL_ORIENT_ANTI_TRANSPOSE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_ANTI_TRANSPOSE_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_ANTI_TRANSPOSE int = _swig_getJXL_ORIENT_ANTI_TRANSPOSE()
func _swig_getJXL_ORIENT_ROTATE_90_CCW() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_ORIENT_ROTATE_90_CCW_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_ORIENT_ROTATE_90_CCW int = _swig_getJXL_ORIENT_ROTATE_90_CCW()
type JxlExtraChannelType int
func _swig_getJXL_CHANNEL_ALPHA() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_ALPHA_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_ALPHA int = _swig_getJXL_CHANNEL_ALPHA()
func _swig_getJXL_CHANNEL_DEPTH() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_DEPTH_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_DEPTH int = _swig_getJXL_CHANNEL_DEPTH()
func _swig_getJXL_CHANNEL_SPOT_COLOR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_SPOT_COLOR_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_SPOT_COLOR int = _swig_getJXL_CHANNEL_SPOT_COLOR()
func _swig_getJXL_CHANNEL_SELECTION_MASK() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_SELECTION_MASK_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_SELECTION_MASK int = _swig_getJXL_CHANNEL_SELECTION_MASK()
func _swig_getJXL_CHANNEL_BLACK() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_BLACK_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_BLACK int = _swig_getJXL_CHANNEL_BLACK()
func _swig_getJXL_CHANNEL_CFA() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_CFA_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_CFA int = _swig_getJXL_CHANNEL_CFA()
func _swig_getJXL_CHANNEL_THERMAL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_THERMAL_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_THERMAL int = _swig_getJXL_CHANNEL_THERMAL()
func _swig_getJXL_CHANNEL_RESERVED0() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED0_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED0 int = _swig_getJXL_CHANNEL_RESERVED0()
func _swig_getJXL_CHANNEL_RESERVED1() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED1_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED1 int = _swig_getJXL_CHANNEL_RESERVED1()
func _swig_getJXL_CHANNEL_RESERVED2() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED2_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED2 int = _swig_getJXL_CHANNEL_RESERVED2()
func _swig_getJXL_CHANNEL_RESERVED3() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED3_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED3 int = _swig_getJXL_CHANNEL_RESERVED3()
func _swig_getJXL_CHANNEL_RESERVED4() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED4_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED4 int = _swig_getJXL_CHANNEL_RESERVED4()
func _swig_getJXL_CHANNEL_RESERVED5() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED5_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED5 int = _swig_getJXL_CHANNEL_RESERVED5()
func _swig_getJXL_CHANNEL_RESERVED6() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED6_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED6 int = _swig_getJXL_CHANNEL_RESERVED6()
func _swig_getJXL_CHANNEL_RESERVED7() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_RESERVED7_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_RESERVED7 int = _swig_getJXL_CHANNEL_RESERVED7()
func _swig_getJXL_CHANNEL_UNKNOWN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_UNKNOWN_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_UNKNOWN int = _swig_getJXL_CHANNEL_UNKNOWN()
func _swig_getJXL_CHANNEL_OPTIONAL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JXL_CHANNEL_OPTIONAL_glue_5245479e8dc75ce4())
	return swig_r
}

var JXL_CHANNEL_OPTIONAL int = _swig_getJXL_CHANNEL_OPTIONAL()
type SwigcptrJxlPreviewHeader uintptr

func (p SwigcptrJxlPreviewHeader) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlPreviewHeader) SwigIsJxlPreviewHeader() {
}

func (arg1 SwigcptrJxlPreviewHeader) SetXsize(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlPreviewHeader_xsize_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlPreviewHeader) GetXsize() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlPreviewHeader_xsize_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlPreviewHeader) SetYsize(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlPreviewHeader_ysize_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlPreviewHeader) GetYsize() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlPreviewHeader_ysize_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlPreviewHeader() (_swig_ret JxlPreviewHeader) {
	var swig_r JxlPreviewHeader
	swig_r = (JxlPreviewHeader)(SwigcptrJxlPreviewHeader(C._wrap_new_JxlPreviewHeader_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlPreviewHeader(arg1 JxlPreviewHeader) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlPreviewHeader_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlPreviewHeader interface {
	Swigcptr() uintptr
	SwigIsJxlPreviewHeader()
	SetXsize(arg2 uint)
	GetXsize() (_swig_ret uint)
	SetYsize(arg2 uint)
	GetYsize() (_swig_ret uint)
}

type SwigcptrJxlAnimationHeader uintptr

func (p SwigcptrJxlAnimationHeader) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlAnimationHeader) SwigIsJxlAnimationHeader() {
}

func (arg1 SwigcptrJxlAnimationHeader) SetTps_numerator(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlAnimationHeader_tps_numerator_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlAnimationHeader) GetTps_numerator() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlAnimationHeader_tps_numerator_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlAnimationHeader) SetTps_denominator(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlAnimationHeader_tps_denominator_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlAnimationHeader) GetTps_denominator() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlAnimationHeader_tps_denominator_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlAnimationHeader) SetNum_loops(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlAnimationHeader_num_loops_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlAnimationHeader) GetNum_loops() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlAnimationHeader_num_loops_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlAnimationHeader) SetHave_timecodes(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlAnimationHeader_have_timecodes_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlAnimationHeader) GetHave_timecodes() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlAnimationHeader_have_timecodes_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlAnimationHeader() (_swig_ret JxlAnimationHeader) {
	var swig_r JxlAnimationHeader
	swig_r = (JxlAnimationHeader)(SwigcptrJxlAnimationHeader(C._wrap_new_JxlAnimationHeader_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlAnimationHeader(arg1 JxlAnimationHeader) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlAnimationHeader_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlAnimationHeader interface {
	Swigcptr() uintptr
	SwigIsJxlAnimationHeader()
	SetTps_numerator(arg2 uint)
	GetTps_numerator() (_swig_ret uint)
	SetTps_denominator(arg2 uint)
	GetTps_denominator() (_swig_ret uint)
	SetNum_loops(arg2 uint)
	GetNum_loops() (_swig_ret uint)
	SetHave_timecodes(arg2 int)
	GetHave_timecodes() (_swig_ret int)
}

type SwigcptrJxlBasicInfo uintptr

func (p SwigcptrJxlBasicInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlBasicInfo) SwigIsJxlBasicInfo() {
}

func (arg1 SwigcptrJxlBasicInfo) SetHave_container(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_have_container_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetHave_container() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlBasicInfo_have_container_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetXsize(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_xsize_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetXsize() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_xsize_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetYsize(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_ysize_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetYsize() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_ysize_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetBits_per_sample(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_bits_per_sample_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetBits_per_sample() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_bits_per_sample_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetExponent_bits_per_sample(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_exponent_bits_per_sample_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetExponent_bits_per_sample() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_exponent_bits_per_sample_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetIntensity_target(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_intensity_target_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetIntensity_target() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_JxlBasicInfo_intensity_target_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetMin_nits(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_min_nits_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetMin_nits() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_JxlBasicInfo_min_nits_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetRelative_to_max_display(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_relative_to_max_display_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetRelative_to_max_display() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlBasicInfo_relative_to_max_display_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetLinear_below(arg2 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_linear_below_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetLinear_below() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_JxlBasicInfo_linear_below_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetUses_original_profile(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_uses_original_profile_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetUses_original_profile() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlBasicInfo_uses_original_profile_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetHave_preview(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_have_preview_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetHave_preview() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlBasicInfo_have_preview_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetHave_animation(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_have_animation_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetHave_animation() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlBasicInfo_have_animation_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetOrientation(arg2 JxlOrientation) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_orientation_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetOrientation() (_swig_ret JxlOrientation) {
	var swig_r JxlOrientation
	_swig_i_0 := arg1
	swig_r = (JxlOrientation)(C._wrap_JxlBasicInfo_orientation_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetNum_color_channels(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_num_color_channels_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetNum_color_channels() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_num_color_channels_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetNum_extra_channels(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_num_extra_channels_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetNum_extra_channels() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_num_extra_channels_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetAlpha_bits(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_alpha_bits_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetAlpha_bits() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_alpha_bits_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetAlpha_exponent_bits(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_alpha_exponent_bits_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetAlpha_exponent_bits() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlBasicInfo_alpha_exponent_bits_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetAlpha_premultiplied(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_alpha_premultiplied_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetAlpha_premultiplied() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlBasicInfo_alpha_premultiplied_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetPreview(arg2 JxlPreviewHeader) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_JxlBasicInfo_preview_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetPreview() (_swig_ret JxlPreviewHeader) {
	var swig_r JxlPreviewHeader
	_swig_i_0 := arg1
	swig_r = (JxlPreviewHeader)(SwigcptrJxlPreviewHeader(C._wrap_JxlBasicInfo_preview_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetAnimation(arg2 JxlAnimationHeader) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_JxlBasicInfo_animation_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetAnimation() (_swig_ret JxlAnimationHeader) {
	var swig_r JxlAnimationHeader
	_swig_i_0 := arg1
	swig_r = (JxlAnimationHeader)(SwigcptrJxlAnimationHeader(C._wrap_JxlBasicInfo_animation_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrJxlBasicInfo) SetPadding(arg2 *byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlBasicInfo_padding_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrJxlBasicInfo) GetPadding() (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1
	swig_r = (*byte)(C._wrap_JxlBasicInfo_padding_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlBasicInfo() (_swig_ret JxlBasicInfo) {
	var swig_r JxlBasicInfo
	swig_r = (JxlBasicInfo)(SwigcptrJxlBasicInfo(C._wrap_new_JxlBasicInfo_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlBasicInfo(arg1 JxlBasicInfo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlBasicInfo_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlBasicInfo interface {
	Swigcptr() uintptr
	SwigIsJxlBasicInfo()
	SetHave_container(arg2 int)
	GetHave_container() (_swig_ret int)
	SetXsize(arg2 uint)
	GetXsize() (_swig_ret uint)
	SetYsize(arg2 uint)
	GetYsize() (_swig_ret uint)
	SetBits_per_sample(arg2 uint)
	GetBits_per_sample() (_swig_ret uint)
	SetExponent_bits_per_sample(arg2 uint)
	GetExponent_bits_per_sample() (_swig_ret uint)
	SetIntensity_target(arg2 float32)
	GetIntensity_target() (_swig_ret float32)
	SetMin_nits(arg2 float32)
	GetMin_nits() (_swig_ret float32)
	SetRelative_to_max_display(arg2 int)
	GetRelative_to_max_display() (_swig_ret int)
	SetLinear_below(arg2 float32)
	GetLinear_below() (_swig_ret float32)
	SetUses_original_profile(arg2 int)
	GetUses_original_profile() (_swig_ret int)
	SetHave_preview(arg2 int)
	GetHave_preview() (_swig_ret int)
	SetHave_animation(arg2 int)
	GetHave_animation() (_swig_ret int)
	SetOrientation(arg2 JxlOrientation)
	GetOrientation() (_swig_ret JxlOrientation)
	SetNum_color_channels(arg2 uint)
	GetNum_color_channels() (_swig_ret uint)
	SetNum_extra_channels(arg2 uint)
	GetNum_extra_channels() (_swig_ret uint)
	SetAlpha_bits(arg2 uint)
	GetAlpha_bits() (_swig_ret uint)
	SetAlpha_exponent_bits(arg2 uint)
	GetAlpha_exponent_bits() (_swig_ret uint)
	SetAlpha_premultiplied(arg2 int)
	GetAlpha_premultiplied() (_swig_ret int)
	SetPreview(arg2 JxlPreviewHeader)
	GetPreview() (_swig_ret JxlPreviewHeader)
	SetAnimation(arg2 JxlAnimationHeader)
	GetAnimation() (_swig_ret JxlAnimationHeader)
	SetPadding(arg2 *byte)
	GetPadding() (_swig_ret *byte)
}

type SwigcptrJxlExtraChannelInfo uintptr

func (p SwigcptrJxlExtraChannelInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlExtraChannelInfo) SwigIsJxlExtraChannelInfo() {
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetXtype(arg2 JxlExtraChannelType) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_Xtype_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetXtype() (_swig_ret JxlExtraChannelType) {
	var swig_r JxlExtraChannelType
	_swig_i_0 := arg1
	swig_r = (JxlExtraChannelType)(C._wrap_JxlExtraChannelInfo_Xtype_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetBits_per_sample(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_bits_per_sample_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetBits_per_sample() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlExtraChannelInfo_bits_per_sample_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetExponent_bits_per_sample(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_exponent_bits_per_sample_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetExponent_bits_per_sample() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlExtraChannelInfo_exponent_bits_per_sample_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetDim_shift(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_dim_shift_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetDim_shift() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlExtraChannelInfo_dim_shift_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetName_length(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_name_length_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetName_length() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlExtraChannelInfo_name_length_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetAlpha_premultiplied(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_alpha_premultiplied_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetAlpha_premultiplied() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlExtraChannelInfo_alpha_premultiplied_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetSpot_color(arg2 *float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_spot_color_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetSpot_color() (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1
	swig_r = (*float32)(C._wrap_JxlExtraChannelInfo_spot_color_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlExtraChannelInfo) SetCfa_channel(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlExtraChannelInfo_cfa_channel_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlExtraChannelInfo) GetCfa_channel() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlExtraChannelInfo_cfa_channel_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlExtraChannelInfo() (_swig_ret JxlExtraChannelInfo) {
	var swig_r JxlExtraChannelInfo
	swig_r = (JxlExtraChannelInfo)(SwigcptrJxlExtraChannelInfo(C._wrap_new_JxlExtraChannelInfo_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlExtraChannelInfo(arg1 JxlExtraChannelInfo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlExtraChannelInfo_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlExtraChannelInfo interface {
	Swigcptr() uintptr
	SwigIsJxlExtraChannelInfo()
	SetXtype(arg2 JxlExtraChannelType)
	GetXtype() (_swig_ret JxlExtraChannelType)
	SetBits_per_sample(arg2 uint)
	GetBits_per_sample() (_swig_ret uint)
	SetExponent_bits_per_sample(arg2 uint)
	GetExponent_bits_per_sample() (_swig_ret uint)
	SetDim_shift(arg2 uint)
	GetDim_shift() (_swig_ret uint)
	SetName_length(arg2 uint)
	GetName_length() (_swig_ret uint)
	SetAlpha_premultiplied(arg2 int)
	GetAlpha_premultiplied() (_swig_ret int)
	SetSpot_color(arg2 *float32)
	GetSpot_color() (_swig_ret *float32)
	SetCfa_channel(arg2 uint)
	GetCfa_channel() (_swig_ret uint)
}

type SwigcptrJxlHeaderExtensions uintptr

func (p SwigcptrJxlHeaderExtensions) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlHeaderExtensions) SwigIsJxlHeaderExtensions() {
}

func (arg1 SwigcptrJxlHeaderExtensions) SetExtensions(arg2 uint64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlHeaderExtensions_extensions_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_type_21(_swig_i_1))
}

func (arg1 SwigcptrJxlHeaderExtensions) GetExtensions() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_JxlHeaderExtensions_extensions_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlHeaderExtensions() (_swig_ret JxlHeaderExtensions) {
	var swig_r JxlHeaderExtensions
	swig_r = (JxlHeaderExtensions)(SwigcptrJxlHeaderExtensions(C._wrap_new_JxlHeaderExtensions_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlHeaderExtensions(arg1 JxlHeaderExtensions) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlHeaderExtensions_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlHeaderExtensions interface {
	Swigcptr() uintptr
	SwigIsJxlHeaderExtensions()
	SetExtensions(arg2 uint64)
	GetExtensions() (_swig_ret uint64)
}

type SwigcptrJxlFrameHeader uintptr

func (p SwigcptrJxlFrameHeader) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJxlFrameHeader) SwigIsJxlFrameHeader() {
}

func (arg1 SwigcptrJxlFrameHeader) SetDuration(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlFrameHeader_duration_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlFrameHeader) GetDuration() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlFrameHeader_duration_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlFrameHeader) SetTimecode(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlFrameHeader_timecode_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlFrameHeader) GetTimecode() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlFrameHeader_timecode_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlFrameHeader) SetName_length(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlFrameHeader_name_length_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlFrameHeader) GetName_length() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_JxlFrameHeader_name_length_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJxlFrameHeader) SetIs_last(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_JxlFrameHeader_is_last_set_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrJxlFrameHeader) GetIs_last() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_JxlFrameHeader_is_last_get_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJxlFrameHeader() (_swig_ret JxlFrameHeader) {
	var swig_r JxlFrameHeader
	swig_r = (JxlFrameHeader)(SwigcptrJxlFrameHeader(C._wrap_new_JxlFrameHeader_glue_5245479e8dc75ce4()))
	return swig_r
}

func DeleteJxlFrameHeader(arg1 JxlFrameHeader) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_JxlFrameHeader_glue_5245479e8dc75ce4(C.uintptr_t(_swig_i_0))
}

type JxlFrameHeader interface {
	Swigcptr() uintptr
	SwigIsJxlFrameHeader()
	SetDuration(arg2 uint)
	GetDuration() (_swig_ret uint)
	SetTimecode(arg2 uint)
	GetTimecode() (_swig_ret uint)
	SetName_length(arg2 uint)
	GetName_length() (_swig_ret uint)
	SetIs_last(arg2 int)
	GetIs_last() (_swig_ret int)
}


type SwigcptrJxlParallelRunner uintptr
type JxlParallelRunner interface {
	Swigcptr() uintptr;
}
func (p SwigcptrJxlParallelRunner) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrJxlColorEncoding uintptr
type JxlColorEncoding interface {
	Swigcptr() uintptr;
}
func (p SwigcptrJxlColorEncoding) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrJxlMemoryManager uintptr
type JxlMemoryManager interface {
	Swigcptr() uintptr;
}
func (p SwigcptrJxlMemoryManager) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrJxlDecoderStruct uintptr
type JxlDecoderStruct interface {
	Swigcptr() uintptr;
}
func (p SwigcptrJxlDecoderStruct) Swigcptr() uintptr {
	return uintptr(p)
}

